SELECT I.ID, COUNT(D.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS D
    RIGHT OUTER JOIN (SELECT DISTINCT(ID)
                      FROM ECOLI_DATA) AS I
    ON D.PARENT_ID = I.ID
GROUP BY I.ID
ORDER BY I.ID