-- 코드를 입력하세요
SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH, 
    GENDER,
    COUNT(DISTINCT(O.USER_ID)) AS USERS
FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m'), GENDER
ORDER BY YEAR, MONTH, GENDER