-- 코드를 입력하세요
SELECT J.FLAVOR
FROM FIRST_HALF AS F
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS J
    ON F.FLAVOR = J.FLAVOR
GROUP BY J.FLAVOR
ORDER BY IFNULL(F.TOTAL_ORDER, 0) + J.TOTAL_ORDER DESC
LIMIT 3